<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\Resources\Icon.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Product>NX File Viewer</Product>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\Resources\Icon.ico" Link="Assets\icon.ico" />
    <AvaloniaResource Include="Assets\Fonts\**"/>
    <EmbeddedResource Include="Assets\locales.json" />
    <AdditionalFiles Include="Assets\locales.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="ConfigFactory.Avalonia" Version="0.6.0" />
    <PackageReference Include="FluentAvaloniaUI" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.1" />
    <PackageReference Include="Optris.Icons.Avalonia" Version="12.0.7" />
    <PackageReference Include="Optris.Icons.Avalonia.FontAwesome" Version="12.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NxFileViewer.Core\NxFileViewer.Core.csproj" />
    <ProjectReference Include="..\NxFileViewer.Ava.LocaleGenerator\NxFileViewer.Ava.LocaleGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
